### ISSUE TITLE
Rechnungspostensuche funktioniert nicht

### ISSUE THREAD

**Issue by razilein** [razilein/kassenbuch#111]
Die Suche nach Rechnungsposten funktioniert nicht mehr:
2020-05-16 18:55:43.160 ERROR 19336 --- [http-nio-8080-exec-1] o.s.b.w.servlet.support.ErrorPageFilter  : Forwarding to error page from request [/rechnung] due to exception [could not prepare statement; SQL [SELECT * FROM vrechnung WHERE EXISTS ( SELECT 1 FROM rechnungsposten WHERE rechnungsposten.rechnung_id = vrechnung.id AND (bezeichnung LIKE ? OR seriennummer LIKE ? OR hinweis LIKE ?)) order by rechnungNr desc limit ?]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement]

org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [SELECT * FROM vrechnung WHERE EXISTS ( SELECT 1 FROM rechnungsposten WHERE rechnungsposten.rechnung_id = vrechnung.id AND (bezeichnung LIKE ? OR seriennummer LIKE ? OR hinweis LIKE ?)) order by rechnungNr desc limit ?]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:281) ~[spring-orm-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:255) ~[spring-orm-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:528) ~[spring-orm-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61) ~[spring-tx-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242) ~[spring-tx-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:153) ~[spring-tx-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:149) ~[spring-data-jpa-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at com.sun.proxy.$Proxy139.findByPostenBezeichnungLikeOrPostenSeriennummerLikeOrPostenHinweisLike(Unknown Source) ~[na:na]
	at de.sg.computerinsel.tools.rechnung.service.RechnungService.listRechnungen(RechnungService.java:71) ~[classes/:2.4.1]

* Schrift auf Bestellungen soll kleiner sein
* Beim E-Mail-Versand von Überweisungsrechnungen soll der gesonderte Druckdialog nicht geöffnet werden da die Rechnung zuvor händisch gedruckt und gleichzeitig als PDF exportiert wird

**Comment by razilein** [comment]
Erledigt mit #112
